server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: turma-service
          uri: lb://turma-service
          predicates:
            - Path=/api/turmas/**
          filters:
            - RewritePath=/api/turmas/(?<segment>.*), /${segment}
        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/api/usuarios/**
          filters:
            - RewritePath=/api/usuarios/(?<segment>.*), /${segment}
        - id: reserva-service
          uri: lb://reserva-service
          predicates:
            - Path=/api/reservas/**
          filters:
            - RewritePath=/api/reservas/(?<segment>.*), /${segment}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
